# Generated by Django 6.1.1 on 2026-09-11 22:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('headline', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('button_text', models.CharField(default='View Profile', max_length=100)),
                ('button_url', models.URLField(blank=True, max_length=500)),
                ('template', models.CharField(choices=[('minimal', 'Minimal'), ('modern', 'Modern'), ('premium', 'Premium')], default='modern', max_length=20)),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='landing_page', to='profiles.socialprofile')),
            ],
        ),
    ]
